name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_PORT: 5433
      DB_NAME: test
      DB_USER: test
      DB_PASS: test
      DB_HOST: localhost
      PYTEST: '1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run linters (flake8, isort, black, mypy)
        run: |
          poetry run black . --check
          poetry run isort . --check-only
          poetry run flake8
          poetry run mypy app/

      - name: Run alembic migrations
        run: poetry run alembic upgrade head

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=app --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
