name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5435:5432
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_PORT: 5435
      DB_NAME: test
      DB_USER: test
      DB_PASS: test
      DB_HOST: localhost
      PYTEST: '1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Check Docker Compose version
        run: docker compose version

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run linters (flake8, isort, black, mypy)
        run: |
          poetry run black . --check
          poetry run isort . --check-only
          poetry run flake8
         

      - name: Run alembic migrations
        run: poetry run alembic upgrade head

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=app --cov-report=term-missing

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

      - name: Stop existing containers
        run: docker compose -f docker-compose-tests.yml down || true

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        if: false
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build Docker image
        if: false
        run: |
          docker build -t ${{ secrets.USERNAME }}/myapp:latest .

      - name: Push Docker image
        if: false
        run: |
          docker push ${{ secrets.USERNAME }}/myapp:latest
      


